In [2]:
import numpy as np
import matplotlib.pyplot as plt
from utils import tensorprod, conj_tp, bra_ket, expectation
from gates import CX, H, rx, ry, rz, cry, p

In [9]:
I = np.eye(2)

In [10]:
Zero = np.array([1, 0]).reshape(-1, 1)
One = np.array([0, 1]).reshape(-1, 1)  

In [36]:
def Ansatz(x):
    # theta = np.array(theta)    
    init  = tensorprod(Zero, Zero, Zero, Zero)
    l_1  = tensorprod(H, H, H, H)
    l_2 = tensorprod(p(2 * x[0]), p(2 * x[1]), p(2 * x[2]), p(2 * x[3]))
    l_3 = tensorprod(CX, CX)
    l_4 = tensorprod(I, p(2 * (np.pi-x[0]) * (np.pi-x[1])), I, p(2 * (np.pi-x[2]) * (np.pi-x[3])))
    l_5 = tensorprod(CX, CX)
    l_6 = tensorprod(I, CX, I)
    l_7 = tensorprod(I, I, p(2 * (np.pi-x[1]) * (np.pi-x[2])), I)
    l_8 = tensorprod(I, CX, I)
    # l_1 = tensorprod(rx(theta[0]), I_)
    # l_2 = cry(theta[1])
    return l_8 @ l_7 @ l_6 @ l_5 @ l_4 @ l_3 @ l_2 @ l_1 @ init

In [37]:
p(np.pi)

array([[ 1.+0.0000000e+00j,  0.+0.0000000e+00j],
       [ 0.+0.0000000e+00j, -1.+1.2246468e-16j]])

In [38]:
from sklearn.datasets import make_classification
X, y  = make_classification(1000, 4, random_state=137)

In [39]:
X[0]

array([-0.03639866,  0.54293503, -1.15013647,  0.99478782])

In [47]:
Ansatz(X[0])

array([[ 0.25      +0.j        ],
       [ 0.00094174+0.24999823j],
       [ 0.18577687+0.16729302j],
       [-0.24999836-0.00090584j],
       [-0.14898864+0.20075454j],
       [-0.20131435-0.14823135j],
       [-0.16910788+0.18412639j],
       [ 0.00335888-0.24997743j],
       [-0.18524595-0.16788073j],
       [ 0.16718172-0.18587703j],
       [-0.02531656-0.24871484j],
       [ 0.18463644+0.16855084j],
       [-0.06025166-0.24263087j],
       [ 0.24240218-0.06116522j],
       [-0.03462587-0.24759049j],
       [ 0.19082743+0.16150817j]])

In [46]:
np.conj(Ansatz(X[0])).reshape(-1) @ Ansatz(X[0])

array([1.+0.j])